project_id_env: GM9_CROWDIN_ID
api_token_env: CROWDIN_TOKEN
preserve_hierarchy: true

files:
  - source: /resources/gm9/languages/en.json
    translation: /resources/gm9/languages/%two_letters_code%.json
